# essential-playerinfo
# Configuration version. !Please do not change this option!
[version]
    version="v3.0"

# Global tablist
[tabList]
    enabled=true

# Global massage
[message]
    enabled=true
    command-to-broadcast=false

# Ping List
[pingList]
    enabled=true

# Connection Tips
[connectionTips]
    enabled=true

# Remember me
[rememberMe]
    enable=true

# Custom Message Setting
[customText]
enable = false
# custom word, if you do not want to send anything in a option, just leave it blank with ""
# e.g. connectionText = ""
# e.g. WDRshadow: Connect to [Server1].
connectionText = "&7%player%: Connect to [%server%]."
# e.g. WDRshadow: [Server1] -> [Server2]
serverChangeText = "&7%player%: [%previousServer%] -> [%server%]"
# e.g. WDRshadow: Exit the servers.
disconnectionText = "&7%player%: Exit the servers."
# e.g. [Server1] <WDRshadow> Hello World!
chatText = "&7[%server%] <%player%> "
