# essential-playerinfo
# Global tablist
[tabList]
    enabled=true

# Global massage
[message]
    enabled=true
    command-to-broadcast=false

# Ping List
[pingList]
    enabled=true

# Connection Tips
[connectionTips]
    enabled=true

