# essential-playerinfo
# Configuration version. !Please do not change this option!
[version]
    version="v3.0"

# Global tablist
[tabList]
    enabled=true

# Global massage
[message]
    enabled=true
    command-to-broadcast=false

# Ping List
[pingList]
    enabled=true

# Connection Tips
[connectionTips]
    enabled=true

# Remember me
[rememberMe]
    enabled=true

# Custom Message Setting
[customText]
    enabled = false
    connectionText = "&7%player%: Connect to [%server%]."
    serverChangeText = "&7%player%: [%previousServer%] -> [%server%]"
    disconnectionText = "&7%player%: Exit the servers."
    chatText = "&7[%server%] <%player%> "
